// sign in types
export const CURRENT_CUSTOMER_INFO = 'CURRENT_CUSTOMER_INFO';
export const CURRENT_TASKER_INFO = 'CURRENT_TASKER_INFO';

// sign up types
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_PASSWORD = 'CREATE_PASSWORD';


// forgot password
export const CUSTOMER_FORGOT_PASSWORD = 'CUSTOMER_FORGOT_PASSWORD';
export const TASKER_FORGOT_PASSWORD = 'TASKER_FORGOT_PASSWORD';


// update password
export const CUSTOMER_UPDATE_PASSWORD = 'CUSTOMER_UPDATE_PASSWORD';
export const TASKER_UPDATE_PASSWORD = 'TASKER_UPDATE_PASSWORD';
